# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-31 13:57
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180331_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tax2',
            field=otree.db.models.PositiveIntegerField(choices=[('Sí', 'Sí'), ('No', 'No')], null=True, verbose_name='¿Pagarías menores impuestos al Estado, sabiendo que la probabilidad de ser atrapado es mínima?'),
        ),
    ]
